//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.20 at 12:27:00 PM IST 
//


package com.sandy.services.soap;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for designation.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="designation">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SE"/>
 *     &lt;enumeration value="SSE"/>
 *     &lt;enumeration value="TL"/>
 *     &lt;enumeration value="ARCHITECT"/>
 *     &lt;enumeration value="PM"/>
 *     &lt;enumeration value="TESTER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "designation")
@XmlEnum
public enum Designation {

    SE,
    SSE,
    TL,
    ARCHITECT,
    PM,
    TESTER;

    public String value() {
        return name();
    }

    public static Designation fromValue(String v) {
        return valueOf(v);
    }

}
